import json
import shutil
from html import escape
from pathlib import Path

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import (
    ParagraphStyle,
    getSampleStyleSheet
)
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

from .gemini_client import GeminiClient
from .report_prompt import build_report_prompt
from .ranking import update_cost_savings, write_rankings
    

# GridAlign repository root
PROJECT_ROOT = Path(__file__).resolve().parents[2]

MATCHES_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "matches.json"
)

REPORTS_DIR = (
    PROJECT_ROOT
    / "reports"
)

RANKINGS_FILE = (
    PROJECT_ROOT
    / "data"
    / "rankings"
    / "priority_rankings.json"
)


# TEST ONLY
# Change to None later to process every match.
TEST_LIMIT = None


def reset_reports_folder():
    """
    Delete reports from the previous run
    and create a completely fresh folder.
    """

    if REPORTS_DIR.exists():
        shutil.rmtree(
            REPORTS_DIR
        )

    REPORTS_DIR.mkdir(
        parents=True,
        exist_ok=True
    )


def load_matches():
    """
    Load candidate matches generated by Java.
    """

    if not MATCHES_FILE.exists():
        raise FileNotFoundError(
            f"Matches file not found: "
            f"{MATCHES_FILE}"
        )

    with MATCHES_FILE.open(
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    matches = data.get(
        "matches",
        []
    )

    if TEST_LIMIT is not None:
        matches = matches[:TEST_LIMIT]

    return matches


def clean_text(text: str) -> str:
    """
    Replace characters that can cause problems
    with the standard PDF font.
    """

    replacements = {
        "–": "-",
        "—": "-",
        "→": "->",
        "↔": "<->",
        "•": "-",
        "“": '"',
        "”": '"',
        "’": "'",
        "‘": "'",
    }

    for old, new in replacements.items():
        text = text.replace(
            old,
            new
        )

    return text


def create_pdf(
    match: dict,
    report_text: str,
    output_file: Path
):
    """
    Create one readable GridAlign PDF report.
    """

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "GridAlignTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "GridAlignSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        alignment=TA_CENTER,
        spaceAfter=18,
    )

    heading_style = ParagraphStyle(
        "GridAlignHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        spaceBefore=10,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "GridAlignBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        spaceAfter=6,
    )

    bullet_style = ParagraphStyle(
        "GridAlignBullet",
        parent=body_style,
        leftIndent=14,
        firstLineIndent=-8,
        spaceAfter=4,
    )

    assessment_style = ParagraphStyle(
        "GridAlignAssessment",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        alignment=TA_CENTER,
        spaceBefore=8,
        spaceAfter=8,
    )

    document = SimpleDocTemplate(
        str(output_file),
        pagesize=letter,
        rightMargin=0.7 * inch,
        leftMargin=0.7 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title="GridAlign Coordination Report",
    )

    project_a = clean_text(
        match["project_a"]["project_name"]
    )

    project_b = clean_text(
        match["project_b"]["project_name"]
    )

    company_a = clean_text(
        match["company_a"]
    )

    company_b = clean_text(
        match["company_b"]
    )

    distance = match["distance_km"]

    story = []

    story.append(
        Paragraph(
            "GRIDALIGN",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Coordination Opportunity Report",
            subtitle_style
        )
    )

    story.append(
        Paragraph(
            f"<b>{escape(company_a)}</b><br/>"
            f"{escape(project_a)}",
            body_style
        )
    )

    story.append(
        Spacer(
            1,
            0.05 * inch
        )
    )

    story.append(
        Paragraph(
            f"<b>Distance between closest known points:</b> "
            f"{distance:.2f} km",
            body_style
        )
    )

    story.append(
        Spacer(
            1,
            0.05 * inch
        )
    )

    story.append(
        Paragraph(
            f"<b>{escape(company_b)}</b><br/>"
            f"{escape(project_b)}",
            body_style
        )
    )

    story.append(
        Spacer(
            1,
            0.2 * inch
        )
    )

    report_text = clean_text(
        report_text
    )

    known_headings = {
        "GRIDALIGN COORDINATION REPORT",
        "PROJECTS",
        "WHY GRIDALIGN FLAGGED THIS PAIR",
        "GEOGRAPHIC ANALYSIS",
        "TIMELINE ANALYSIS",
        "COORDINATION OPPORTUNITIES",
        "POTENTIAL BENEFITS",
        "COST-SAVING OPPORTUNITIES",
        "RISKS AND LIMITATIONS",
        "FINAL ASSESSMENT",
        "RECOMMENDED NEXT STEP",
    }

    assessments = {
        "HIGH",
        "MEDIUM",
        "LOW",
        "NO OPPORTUNITY",
    }

    for raw_line in report_text.splitlines():

        line = raw_line.strip()

        if not line:
            story.append(
                Spacer(
                    1,
                    0.06 * inch
                )
            )
            continue

        # Remove simple Markdown heading symbols
        line = line.lstrip("#").strip()

        safe_line = escape(line)

        if line.upper() in known_headings:

            # We already create our own title
            if (
                line.upper()
                == "GRIDALIGN COORDINATION REPORT"
            ):
                continue

            story.append(
                Paragraph(
                    safe_line,
                    heading_style
                )
            )

        elif line.upper() in assessments:

            story.append(
                Paragraph(
                    safe_line,
                    assessment_style
                )
            )

        elif (
            line.startswith("- ")
            or line.startswith("* ")
        ):

            bullet_text = (
                line[2:].strip()
            )

            story.append(
                Paragraph(
                    "• "
                    + escape(bullet_text),
                    bullet_style
                )
            )

        else:

            story.append(
                Paragraph(
                    safe_line,
                    body_style
                )
            )

    document.build(
        story
    )


def generate_reports():
    """
    Generate GridAlign AI reports.

    For now only the first two matches
    are processed for testing.
    """

    print()
    print("=" * 60)
    print("GRIDALIGN AI REPORT GENERATION")
    print("=" * 60)

    matches = load_matches()

    if not matches:
        print(
            "No matches were found."
        )
        return

    matches_with_ids = [
        {
            **match,
            "match_id": index,
        }
        for index, match in enumerate(matches, start=1)
    ]
    write_rankings(
        matches_with_ids,
        RANKINGS_FILE,
    )

    # Always start with a fresh reports folder
    reset_reports_folder()

    gemini = GeminiClient()

    total = len(matches)

    print()
    print(
        f"Matches to process: {total}"
    )
    print()

    for index, match in enumerate(
        matches,
        start=1
    ):

        project_a = (
            match["project_a"]
            ["project_name"]
        )

        project_b = (
            match["project_b"]
            ["project_name"]
        )

        distance = (
            match["distance_km"]
        )

        print("=" * 60)
        print(
            f"Report {index}/{total}"
        )
        print(
            project_a
        )
        print(
            "<->"
        )
        print(
            project_b
        )
        print(
            f"Distance: {distance} km"
        )
        print("=" * 60)

        prompt = (
            build_report_prompt(
                match
            )
        )

        report_text = (
            gemini.generate_report(
                prompt
            )
        )

        update_cost_savings(
            index,
            report_text,
            RANKINGS_FILE,
        )

        output_file = (
            REPORTS_DIR
            / f"match_{index}.pdf"
        )

        create_pdf(
            match=match,
            report_text=report_text,
            output_file=output_file
        )

        print(
            f"Saved: {output_file}"
        )
        print()

    print("=" * 60)
    print(
        f"Reports generated: {total}"
    )
    print(
        f"Reports folder: {REPORTS_DIR}"
    )
    print("=" * 60)